/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.CurrentWeatherTableModel;
import BL.Destination;
import BL.Forecast5DayTableModel;
import java.time.LocalDate;
import java.util.ArrayList;

/**
 *
 * @author vizug
 */
public class ForeCastGUI extends javax.swing.JFrame {

    CurrentWeatherTableModel cwm = new CurrentWeatherTableModel();
    Forecast5DayTableModel ftm = new Forecast5DayTableModel();

    /**
     * Creates new form ForeCastGUI
     */
    public ForeCastGUI() {
        initComponents();
        //will display the dates for the next five days from now on 
        LocalDate date = LocalDate.now();
        for (int i = 0; i < 5; i++) {
            this.cbProposedDay.addItem(date.plusDays(i).toString());
        }

    }

    /**
     * fills the table with the one day forecast and displays it. the table
     * model and the cellrenderer will be changed
     *
     * @param destinations
     */
    public void showForecasts(ArrayList<Destination> destinations) {
        tbForecasts.setDefaultRenderer(Object.class, new ForecastCellRenderer());
        tbForecasts.setModel(cwm);
        cwm.showForeCasts(destinations);
        btCheckProposedDay.setVisible(false);
        cbProposedDay.setVisible(false);
    }

    /**
     * fills the table with the five day forecast and displays it. the table
     * model and the cellrenderer will be changed
     *
     * @param destinations
     */
    public void show5DayForecast(ArrayList<Destination> destinations) {
        tbForecasts.setDefaultRenderer(Object.class, new ForeCast5DaysCellRenderer());
        tbForecasts.setModel(ftm);
        ftm.show5DayForeCasts(destinations);
        btCheckProposedDay.setVisible(true);
        cbProposedDay.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        miSortByTemp = new javax.swing.JMenuItem();
        miSortByHum = new javax.swing.JMenuItem();
        miSortByPressure = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbForecasts = new javax.swing.JTable();
        cbProposedDay = new javax.swing.JComboBox<>();
        btCheckProposedDay = new javax.swing.JButton();

        miSortByTemp.setText("sort by Temperature");
        miSortByTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSortByTempActionPerformed(evt);
            }
        });
        jPopupMenu1.add(miSortByTemp);

        miSortByHum.setText("sort by Humidity");
        miSortByHum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSortByHumActionPerformed(evt);
            }
        });
        jPopupMenu1.add(miSortByHum);

        miSortByPressure.setText("sort by Pressure");
        miSortByPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSortByPressureActionPerformed(evt);
            }
        });
        jPopupMenu1.add(miSortByPressure);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tbForecasts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbForecasts.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tbForecasts);

        cbProposedDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProposedDayActionPerformed(evt);
            }
        });

        btCheckProposedDay.setText("check Proposed Day");
        btCheckProposedDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCheckProposedDayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCheckProposedDay, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(cbProposedDay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cbProposedDay, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCheckProposedDay)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbProposedDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProposedDayActionPerformed

    }//GEN-LAST:event_cbProposedDayActionPerformed

    private void btCheckProposedDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCheckProposedDayActionPerformed
        String date = (String) cbProposedDay.getSelectedItem();
        //will call the methode in the table model and will filter the list
        ftm.showProposedDay(date);
    }//GEN-LAST:event_btCheckProposedDayActionPerformed

    private void miSortByTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSortByTempActionPerformed
        ftm.sortByTemp();
    }//GEN-LAST:event_miSortByTempActionPerformed

    private void miSortByHumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSortByHumActionPerformed
        ftm.sortByHum();
    }//GEN-LAST:event_miSortByHumActionPerformed

    private void miSortByPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSortByPressureActionPerformed
        ftm.sortByPressure();
    }//GEN-LAST:event_miSortByPressureActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForeCastGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForeCastGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForeCastGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForeCastGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForeCastGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCheckProposedDay;
    private javax.swing.JComboBox<String> cbProposedDay;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miSortByHum;
    private javax.swing.JMenuItem miSortByPressure;
    private javax.swing.JMenuItem miSortByTemp;
    private javax.swing.JTable tbForecasts;
    // End of variables declaration//GEN-END:variables
}
